-- MySQL Script generated by MySQL Workbench
-- 08/02/15 22:26:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ned
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ned
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ned` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ned` ;

-- -----------------------------------------------------
-- Table `ned`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`user` (
  `id_user` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_email` VARCHAR(45) NOT NULL COMMENT '',
  `st_cpfCnpj` VARCHAR(45) NULL COMMENT '',
  `st_password` VARCHAR(45) NULL COMMENT '',
  `dt_dateCreate` DATETIME NOT NULL COMMENT '',
  `dt_dateAlter` DATETIME NOT NULL COMMENT '',
  `active` BIT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`st_email` ASC)  COMMENT '',
  UNIQUE INDEX `st_cpfCnpj_UNIQUE` (`st_cpfCnpj` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`education` (
  `id_education` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_education` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_education`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`PostJob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`PostJob` (
  `id_Post` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_post` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_Post`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`userProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`userProfile` (
  `id_userProfile` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_user` BIGINT NOT NULL COMMENT '',
  `st_name` VARCHAR(45) NOT NULL COMMENT '',
  `dt_birthDate` DATETIME NOT NULL COMMENT '',
  `id_education` INT NOT NULL COMMENT '',
  `id_PostJob` INT NOT NULL COMMENT '',
  `bit_oab` BIT NULL DEFAULT 0 COMMENT '',
  `bit_certDigital` BIT NULL DEFAULT 0 COMMENT '',
  `st_site` VARCHAR(45) NULL COMMENT '',
  `st_about` VARCHAR(200) NULL COMMENT '',
  `st_describe` VARCHAR(200) NULL COMMENT '',
  `dt_dateCreate` DATETIME NULL COMMENT '',
  `dt_dateAlter` DATETIME NULL COMMENT '',
  `bit_active` BIT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id_userProfile`, `id_user`, `id_education`, `id_PostJob`)  COMMENT '',
  INDEX `fk_user_profile_user_idx` (`id_user` ASC)  COMMENT '',
  INDEX `fk_user_profile_education1_idx` (`id_education` ASC)  COMMENT '',
  INDEX `fk_userProfile_Post1_idx` (`id_PostJob` ASC)  COMMENT '',
  CONSTRAINT `fk_user_profile_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `ned`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profile_education1`
    FOREIGN KEY (`id_education`)
    REFERENCES `ned`.`education` (`id_education`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userProfile_Post1`
    FOREIGN KEY (`id_PostJob`)
    REFERENCES `ned`.`PostJob` (`id_Post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`phoneType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`phoneType` (
  `id_phoneType` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_phoneType` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_phoneType`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`phones` (
  `id_UserProfile` BIGINT NOT NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `ddd` VARCHAR(45) NOT NULL COMMENT '',
  `id_phoneType` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_UserProfile`, `id_phoneType`)  COMMENT '',
  INDEX `fk_phones_user_profile1_idx` (`id_UserProfile` ASC)  COMMENT '',
  INDEX `fk_phones_phoneType1_idx` (`id_phoneType` ASC)  COMMENT '',
  CONSTRAINT `fk_phones_user_profile1`
    FOREIGN KEY (`id_UserProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_phoneType1`
    FOREIGN KEY (`id_phoneType`)
    REFERENCES `ned`.`phoneType` (`id_phoneType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`State` (
  `id_State` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_state` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_State`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`City` (
  `id_City` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_city` VARCHAR(45) NOT NULL COMMENT '',
  `id_State` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_City`, `id_State`)  COMMENT '',
  INDEX `fk_City_State1_idx` (`id_State` ASC)  COMMENT '',
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`id_State`)
    REFERENCES `ned`.`State` (`id_State`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`UserCitiesServed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`UserCitiesServed` (
  `id_userProfile` BIGINT NOT NULL COMMENT '',
  `id_City` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_userProfile`, `id_City`)  COMMENT '',
  INDEX `fk_citiesServed_userProfile1_idx` (`id_userProfile` ASC)  COMMENT '',
  INDEX `fk_CitiesServed_City1_idx` (`id_City` ASC)  COMMENT '',
  CONSTRAINT `fk_citiesServed_userProfile1`
    FOREIGN KEY (`id_userProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CitiesServed_City1`
    FOREIGN KEY (`id_City`)
    REFERENCES `ned`.`City` (`id_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`Oab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`Oab` (
  `id_userProfile` BIGINT NOT NULL COMMENT '',
  `st_number` INT(6) NULL COMMENT '',
  `id_State` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_userProfile`, `id_State`)  COMMENT '',
  INDEX `fk_Oab_State1_idx` (`id_State` ASC)  COMMENT '',
  CONSTRAINT `fk_Oab_userProfile1`
    FOREIGN KEY (`id_userProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oab_State1`
    FOREIGN KEY (`id_State`)
    REFERENCES `ned`.`State` (`id_State`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`Speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`Speciality` (
  `id_Speciality` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_Speciality` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_Speciality`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`UserSpecialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`UserSpecialities` (
  `id_userProfile` BIGINT NOT NULL COMMENT '',
  `id_Speciality` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_userProfile`, `id_Speciality`)  COMMENT '',
  INDEX `fk_UserSpeciality_Speciality1_idx` (`id_Speciality` ASC)  COMMENT '',
  CONSTRAINT `fk_UserSpeciality_userProfile1`
    FOREIGN KEY (`id_userProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserSpeciality_Speciality1`
    FOREIGN KEY (`id_Speciality`)
    REFERENCES `ned`.`Speciality` (`id_Speciality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`services` (
  `id_services` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `st_service` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_services`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`UserAttendedServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`UserAttendedServices` (
  `id_services` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_userProfile` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`id_services`, `id_userProfile`)  COMMENT '',
  INDEX `fk_UserAttendedServices_userProfile1_idx` (`id_userProfile` ASC)  COMMENT '',
  CONSTRAINT `fk_UserAttendedServices_services1`
    FOREIGN KEY (`id_services`)
    REFERENCES `ned`.`services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserAttendedServices_userProfile1`
    FOREIGN KEY (`id_userProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ned`.`coments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned`.`coments` (
  `id_userProfile` BIGINT NOT NULL COMMENT '',
  `st_name` VARCHAR(45) NOT NULL COMMENT '',
  `st_email` VARCHAR(45) NOT NULL COMMENT '',
  `st_job` VARCHAR(45) NOT NULL COMMENT '',
  `st_comment` VARCHAR(500) NOT NULL COMMENT '',
  `id_City` INT NOT NULL COMMENT '',
  `dt_dateCreate` DATETIME NOT NULL COMMENT '',
  `dt_dateAlter` DATETIME NOT NULL COMMENT '',
  `bit_active` BIT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`id_userProfile`, `id_City`)  COMMENT '',
  INDEX `fk_coments_City1_idx` (`id_City` ASC)  COMMENT '',
  CONSTRAINT `fk_coments_userProfile1`
    FOREIGN KEY (`id_userProfile`)
    REFERENCES `ned`.`userProfile` (`id_userProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coments_City1`
    FOREIGN KEY (`id_City`)
    REFERENCES `ned`.`City` (`id_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
