-- MySQL Script generated by MySQL Workbench
-- 09/20/15 01:56:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ned_novo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ned_novo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ned_novo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ned_novo` ;

-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_estado` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT COMMENT ''
,  `st_estado` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_estado`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_cidade` (
  `id_cidade` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_cidade` VARCHAR(45) NOT NULL COMMENT '',
  `id_estado` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_cidade`, `st_cidade`)  COMMENT '',
  INDEX `fk_CORRESP_cidade_CORRESP_estado1_idx` (`id_estado` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_cidade_CORRESP_estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `ned_novo`.`CORRESP_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_usuario` (
  `id_usuario` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_email` VARCHAR(45) NOT NULL COMMENT '',
  `st_cpf_cnpj` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `st_senha` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `dt_data_criacao` DATETIME NOT NULL COMMENT '',
  `dt_data_alteracao` DATETIME NOT NULL COMMENT '',
  `bt_ativo` BIT(1) NULL DEFAULT b'1' COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`st_email` ASC)  COMMENT '',
  UNIQUE INDEX `st_cpf_cnpj_UNIQUE` (`st_cpf_cnpj` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_educacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_educacao` (
  `id_educacao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_educacao` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_educacao`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_tipo_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_tipo_trabalho` (
  `id_tipo_trabalho` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_tipo_trabalho` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_trabalho`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_usuario_perfil` (
  `id_usuario_perfil` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` BIGINT(20) NOT NULL COMMENT '',
  `id_educacao` INT(11) NOT NULL COMMENT '',
  `id_tipo_trabalho` INT(11) NOT NULL COMMENT '',
  `st_nome` VARCHAR(45) NOT NULL COMMENT '',
  `dt_data_nascimento` DATETIME NOT NULL COMMENT '',
  `bt_oab` BIT(1) NULL DEFAULT b'0' COMMENT '',
  `bt_cert_Digital` BIT(1) NULL DEFAULT b'0' COMMENT '',
  `st_site` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `st_sobre` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `st_descricao` VARCHAR(200) NULL COMMENT '',
  `dt_data_criacao` DATETIME NULL COMMENT '',
  `dt_data_alteracao` DATETIME NULL COMMENT '',
  `bt_ativo` BIT(1) NULL DEFAULT b'1' COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`)  COMMENT '',
  INDEX `fk_CORRESP_usuario_perfil_CORRESP_usuario_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_CORRESP_usuario_perfil_CORRESP_educacao1_idx` (`id_educacao` ASC)  COMMENT '',
  INDEX `fk_CORRESP_usuario_perfil_CORRESP_tipo_trabalho1_idx` (`id_tipo_trabalho` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_usuario_perfil_CORRESP_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ned_novo`.`CORRESP_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_usuario_perfil_CORRESP_educacao1`
    FOREIGN KEY (`id_educacao`)
    REFERENCES `ned_novo`.`CORRESP_educacao` (`id_educacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_usuario_perfil_CORRESP_tipo_trabalho1`
    FOREIGN KEY (`id_tipo_trabalho`)
    REFERENCES `ned_novo`.`CORRESP_tipo_trabalho` (`id_tipo_trabalho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_comentario` (
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  `st_nome` VARCHAR(45) NOT NULL COMMENT '',
  `st_email` VARCHAR(45) NOT NULL COMMENT '',
  `st_trabalho` VARCHAR(45) NOT NULL COMMENT '',
  `st_comentario` VARCHAR(500) NOT NULL COMMENT '',
  `id_cidade` INT(11) NOT NULL COMMENT '',
  `dt_data_criacao` DATETIME NOT NULL COMMENT '',
  `dt_data_alteracao` DATETIME NOT NULL COMMENT '',
  `bt_ativo` BIT(1) NOT NULL DEFAULT b'1' COMMENT '',
  `CORRESP_cidade_id_cidade` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`, `id_cidade`)  COMMENT '',
  INDEX `fk_comentario_cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  INDEX `fk_CORRESP_comentario_CORRESP_usuario_perfil1_idx` (`id_usuario_perfil` ASC)  COMMENT '',
  INDEX `fk_CORRESP_comentario_CORRESP_cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_comentario_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_comentario_CORRESP_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `ned_novo`.`CORRESP_cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_oab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_oab` (
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  `st_numero` INT(6) NULL DEFAULT NULL COMMENT '',
  `id_estado` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`, `id_estado`)  COMMENT '',
  INDEX `fk_Oab_estado_idx` (`id_estado` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_Oab_CORRESP_estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `ned_novo`.`CORRESP_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_Oab_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_telefone_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_telefone_tipo` (
  `id_telefone_tipo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_telefone_tipo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_telefone_tipo`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_telefone` (
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  `id_telefone_tipo` INT(11) NOT NULL COMMENT '',
  `st_telefone` VARCHAR(45) NOT NULL COMMENT '',
  `st_ddd` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`, `id_telefone_tipo`)  COMMENT '',
  INDEX `fk_telefone_usuario_perfil_idx` (`id_usuario_perfil` ASC)  COMMENT '',
  INDEX `fk_telefone_telefone_tipo_idx` (`id_telefone_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_telefone_CORRESP_telefone_tipo1`
    FOREIGN KEY (`id_telefone_tipo`)
    REFERENCES `ned_novo`.`CORRESP_telefone_tipo` (`id_telefone_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_telefone_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_servico` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_servico`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_especialidade` (
  `id_especialidade` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `st_especialidade` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_especialidade`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_usuario_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_usuario_servico` (
  `id_servico` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_servico`, `id_usuario_perfil`)  COMMENT '',
  INDEX `fk_usuario_servico_id_usuario_perfil_idx` (`id_usuario_perfil` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_usuario_servico_CORRESP_servico1`
    FOREIGN KEY (`id_servico`)
    REFERENCES `ned_novo`.`CORRESP_servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_usuario_servico_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_usuario_cidade_atendida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_usuario_cidade_atendida` (
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  `id_cidade` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`, `id_cidade`)  COMMENT '',
  INDEX `fk_usuario_cidade_atendida_id_usuario_perfil1_idx` (`id_usuario_perfil` ASC)  COMMENT '',
  INDEX `fk_usuario_cidade_atendida_cidade_idx` (`id_cidade` ASC)  COMMENT '',
  INDEX `fk_CORRESP_usuario_cidade_atendida_CORRESP_cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_usuario_cidade_atendida_CORRESP_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `ned_novo`.`CORRESP_cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_usuario_cidade_atendida_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ned_novo`.`CORRESP_usuario_especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ned_novo`.`CORRESP_usuario_especialidade` (
  `id_usuario_perfil` BIGINT(20) NOT NULL COMMENT '',
  `id_especialidade` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario_perfil`, `id_especialidade`)  COMMENT '',
  INDEX `fk_usuario_especialidade_id_especialidade_idx` (`id_especialidade` ASC)  COMMENT '',
  CONSTRAINT `fk_CORRESP_usuario_especialidade_CORRESP_especialidade1`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `ned_novo`.`CORRESP_especialidade` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CORRESP_usuario_especialidade_CORRESP_usuario_perfil1`
    FOREIGN KEY (`id_usuario_perfil`)
    REFERENCES `ned_novo`.`CORRESP_usuario_perfil` (`id_usuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
